package com.aicrm.core.global.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {

    INVALID_REQUEST("INVALID_REQUEST", HttpStatus.BAD_REQUEST),
    NOT_FOUND("NOT_FOUND", HttpStatus.NOT_FOUND),
    CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND", HttpStatus.NOT_FOUND),
    INVALID_CATEGORY_DEPTH("INVALID_CATEGORY_DEPTH", HttpStatus.BAD_REQUEST),
    TICKET_NOT_FOUND("TICKET_NOT_FOUND", HttpStatus.NOT_FOUND),
    AGENT_ID_REQUIRED("AGENT_ID_REQUIRED", HttpStatus.BAD_REQUEST),
    TICKET_CANNOT_UPDATE("TICKET_CANNOT_UPDATE", HttpStatus.BAD_REQUEST),
    TICKET_CANNOT_ACCEPT("TICKET_CANNOT_ACCEPT", HttpStatus.BAD_REQUEST),
    TICKET_ALREADY_ASSIGNED("TICKET_ALREADY_ASSIGNED", HttpStatus.CONFLICT),
    TICKET_CANNOT_CLOSE("TICKET_CANNOT_CLOSE", HttpStatus.BAD_REQUEST),
    NOT_ASSIGNED_AGENT("NOT_ASSIGNED_AGENT", HttpStatus.FORBIDDEN),
    RESOLUTION_REQUIRED("RESOLUTION_REQUIRED", HttpStatus.BAD_REQUEST),
    MESSAGE_CONTENT_REQUIRED("MESSAGE_CONTENT_REQUIRED", HttpStatus.BAD_REQUEST),
    TICKET_CANNOT_ADD_MESSAGE("TICKET_CANNOT_ADD_MESSAGE", HttpStatus.BAD_REQUEST),
    INVALID_MESSAGE_TYPE("INVALID_MESSAGE_TYPE", HttpStatus.BAD_REQUEST),
    AUTH_FAILED("AUTH_FAILED", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED("UNAUTHORIZED", HttpStatus.UNAUTHORIZED),
    FORBIDDEN("FORBIDDEN", HttpStatus.FORBIDDEN),
    DUPLICATE_EMAIL("DUPLICATE_EMAIL", HttpStatus.CONFLICT),
    DUPLICATE_EMPLOYEE_NO("DUPLICATE_EMPLOYEE_NO", HttpStatus.CONFLICT),
    INVALID_EMPLOYEE_NO("INVALID_EMPLOYEE_NO", HttpStatus.BAD_REQUEST),
    AGENT_APPROVAL_REQUIRED("AGENT_APPROVAL_REQUIRED", HttpStatus.FORBIDDEN),
    ACCOUNT_UNAVAILABLE("ACCOUNT_UNAVAILABLE", HttpStatus.BAD_REQUEST),
    ACCOUNT_WITHDRAWN("ACCOUNT_WITHDRAWN", HttpStatus.BAD_REQUEST),
    ACCOUNT_SUSPENDED("ACCOUNT_SUSPENDED", HttpStatus.BAD_REQUEST),
    INTERNAL_ERROR("INTERNAL_ERROR", HttpStatus.INTERNAL_SERVER_ERROR);

    private final String code;
    private final HttpStatus status;

    ErrorCode(String code, HttpStatus status) {
        this.code = code;
        this.status = status;
    }

    public String getCode() {
        return code;
    }

    public HttpStatus getStatus() {
        return status;
    }
}
