server:
  port: 8080

spring:
  application:
    name: core-api-service
  datasource:
    url: jdbc:postgresql://localhost:5432/aicrm
    username: aicrm
    password: aicrm
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
